### ISSUE TITLE
Basic installation errors?

### ISSUE THREAD

**Issue by bananabrann** [eleby/pixelizer#3]
I thought this looked super cool, and wanted to give a spin! I'm planning on editing any files, just wanted to have fun and see what the program could do.  I've never used Go, and following the instructions in the README leaves me with a few errors that I suspect are just related to me not knowing Go. However, some basic digging and comparison against the instructions has left me a bit confused on what I'm supposed to do in order to get it working properly.

Pop!_OS 20.10 (Ubuntu-based)
Go 1.16.1 linux/amd64

***

`go get` retrieves nothing, with no errors. So I've cloned the files to ~/Downloads/pixelizer.

```sh
test@pop-os ~/Downloads$ ll
./
../
pixelizer/
```

When building the repository...
```sh
test@pop-os ~/Downloads/pixelizer/main$ go build -o pixelize
go: cannot find main module, but found .git/config in /home/lee/Downloads/pixelizer
	to create a module there, run:
	cd .. && go mod init
```

Alright, I'll be a good boy and do as it says.
```sh
lee@pop-os:~/Downloads/pixelizer/main$ cd .. && go mod init
go: cannot determine module path for source directory /home/lee/Downloads/pixelizer (outside GOPATH, module path must be specified)
```

***

Knowing my unfamiliarity with Go, it's probably something simple. Am I missing something?

Thank you for any and all help!

**Comment by eleby** [comment]
Hello !

The second step in the install procedure, stating to first navigate to your go sources repository, needs you to navigate to what I guess is /users/lee/go before launching the command listed there. 
I hope it solves your problem !

**Comment by bananabrann** [comment]
Thank you for the response! @eleby  😃️ It partially solved it... It caused me to poke around for the repo, and I found it in `~/go/pkg/mod/github.com/eleby/pixelizer@v0.0.0-20210307012652-33effda37b25/`. Is that an expected behavior?

However, still getting an error on the build command.

```sh
lee@pop-os:~/go/pkg/mod/github.com/eleby/pixelizer@v0.0.0-20210307012652-33effda37b25/main$ go build -o pixelize
go: cannot find main module; see 'go help modules'
```


Any ideas?

**Comment by eleby** [comment]
Sorry my answer wasn't complete actually. You must go to /users/lee/go/src instead of just /users/lee/go.

All your go get X commands will install the packages here and it is basically where you might want to place your own projects too 😉

**Comment by bananabrann** [comment]
No problem, thanks for walking through it!

There isn't a src directory in ~/go

```sh
lee@pop-os:~/go$ ll
```

Running the following commands from where there is a src directory, /usr/local/go/ ...
```sh
lee@pop-os:/usr/local/go/src$ go build -o pixelize
go: inconsistent vendoring in /usr/local/go/src:
	github.com/eleby/pixelizer@v0.0.0-20210307012652-33effda37b25: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor

lee@pop-os:/usr/local/go/src$ go build -o pixelize -mod=readonly
no Go files in /usr/local/go/src

lee@pop-os:/usr/local/go/src$ go mod vendor
go: downloading golang.org/x/crypto v0.0.0-20201016220609-9e8e0b390897
go: downloading golang.org/x/net v0.0.0-20201209123823-ac852fbbde11
go: downloading golang.org/x/sys v0.0.0-20201204225414-ed752295db88
go: downloading golang.org/x/text v0.3.4

lee@pop-os:/usr/local/go/src$ go build -o pixelize
no Go files in /usr/local/go/src

```


Do you think this is a bigger issue with my installation of Go itself?

**Comment by eleby** [comment]
Yeah I think so, something seems wrong. You basically should have a go path (~/go by default, else $GOPATH environment variable ) and a go root (/usr/local/go by default or $GOROOT environment variable), each containing their src folder.

Go get installs packages in your gopath. 

If you have a go folder in your home directory maybe adding the src folder and relaunching the go get command would do the trick.

**Comment by bananabrann** [comment]
Thank you for taking the time to walk with me! I'll go off into the distance on my Go journey. Thank you again!

**Comment by eleby** [comment]
Sorry I couldn't find the solution to your issue. It seems like the installation process for this repository may change with the next version, so stay tuned for that ! Have a great go journey 😉

**Comment by ffmiruz** [comment]
@bananabrann If you still want to try this you can try naming your mod. 

So going off from your first comment it can be like this; 

```
test@pop-os ~/Downloads/pixelizer/main$ go mod init foobar
test@pop-os ~/Downloads/pixelizer/main$ go build -o pixelize
```

make sure to build from `main` folder i.e. where the .go files are.
